# S03 T04: Pràctica amb programació numèrica



## Nivell 1

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [108]:
import pandas as pd
import numpy as np
from numpy import random

arr = np.random.randint((100), size=(10))

def resumen_estadistico(arr):
     mean = arr.mean()
     max = arr.max()
     min = arr.min()
     suma = arr.sum() 
     print("El número más grande es el:", max)
     print("El número más pequeño es el:", min) 
     print("La media es de:", mean)
     print("La suma de todos los elementos es de:", suma)
                   
if arr.ndim > 1:
        print ("Error")
else:
  print(arr)
  print("Resumen estadístico básico de los datos") 
  resumen_estadistico(arr)      

[54 44 45 25 10 53 43 77 90 58]
Resumen estadístico básico de los datos
El número más grande es el: 90
El número más pequeño es el: 10
La media es de: 49.9
La suma de todos los elementos es de: 499


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [109]:
def crear_cuadrado():
  base = int(input("Ingrese un número:"))  
  print(np.random.randint((100), size=(base,base)))
    
crear_cuadrado()

Ingrese un número:8
[[97 61 17 27 43 84 41 87]
 [ 8 79 31 10  5 38  4 11]
 [32  1 97 96 12 34 95 44]
 [88 54 16 11 22 86 36 43]
 [94  8 32 79 35 39 98 41]
 [59 45 68 83 18 96  9 46]
 [82 55 35 33 56 37 46  9]
 [84 22 23 25 19 31 54 85]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [111]:
arr = np.random.randint((1000), size=(6,6))

def calcular_totales(arr):
    filas = len(arr)
    columnas = len(arr[0])
    sumaFilas = np.apply_along_axis(sum, 1, arr)
    sumaColumnas = np.apply_along_axis(sum, 0, arr)
    print("La suma de las filas es:", sumaFilas)
    print("La suma de las columnas es:", sumaColumnas)

print(arr)
calcular_totales(arr) 

[[401 301 943 280 693 851]
 [523 133 230 855 517 738]
 [935 996 855 412  20 891]
 [651 696 173 783  55 670]
 [424 918 285 223  69 517]
 [296  99 997 998 692 686]]
La suma de las filas es: [3469 2996 4109 3028 2436 3768]
La suma de las columnas es: [3230 3143 3483 3551 2046 4353]


### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [112]:
def coeficiente_correlacion():
  x = np.array([-2, -1, 0, 1, 2])
  y = np.array([4, 1, 3, 2, 0])
  result = np.corrcoef(x, y)
  print(result)

coeficiente_correlacion()

[[ 1.  -0.7]
 [-0.7  1. ]]
